[2024-07-31 08:31:11,136]\tINFO\t[main.py:lifespan:17]\t>> SERVER STARTING::2024-07-31 08:31:11.136576
[2024-07-31 08:31:11,138]\tINFO\t[on.py:startup:62]\t>> Application startup complete.
[2024-07-31 08:31:11,140]\tINFO\t[server.py:_log_started_message:214]\t>> Uvicorn running on http://0.0.0.0:8989 (Press CTRL+C to quit)
[2024-07-31 08:31:14,193]\tINFO\t[httptools_impl.py:send:466]\t>> 172.20.208.1:58121 - "GET / HTTP/1.1" 200
[2024-07-31 08:31:18,124]\tINFO\t[httptools_impl.py:send:466]\t>> 172.20.208.1:58121 - "GET /docs HTTP/1.1" 200
[2024-07-31 08:31:18,194]\tINFO\t[httptools_impl.py:send:466]\t>> 172.20.208.1:58121 - "GET /openapi.json HTTP/1.1" 200
[2024-07-31 08:31:21,177]\tINFO\t[server.py:shutdown:258]\t>> Shutting down
[2024-07-31 08:31:21,277]\tINFO\t[on.py:shutdown:67]\t>> Waiting for application shutdown.
[2024-07-31 08:31:21,280]\tINFO\t[main.py:lifespan:22]\t>> ::SERVER SHUTTING DOWN::2024-07-31 08:31:21.280385
[2024-07-31 08:31:21,282]\tINFO\t[on.py:shutdown:76]\t>> Application shutdown complete.
[2024-07-31 08:31:21,284]\tINFO\t[server.py:_serve:92]\t>> Finished server process [73150]
[2024-07-31 08:31:21,286]\tERROR\t[logger.py:handle_exception:86]\t>> System-level unexpected exception
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/home/jungwoo/my_qa_bot/fastapi/main.py", line 53, in <module>
    uvicorn.run(
  File "/home/jungwoo/my_qa_bot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/jungwoo/my_qa_bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/jungwoo/my_qa_bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/jungwoo/my_qa_bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
[2024-07-31 08:31:33,854]\tINFO\t[main.py:lifespan:17]\t>> SERVER STARTING::2024-07-31 08:31:33.854959
[2024-07-31 08:31:33,857]\tINFO\t[on.py:startup:62]\t>> Application startup complete.
[2024-07-31 08:31:33,858]\tINFO\t[server.py:_log_started_message:214]\t>> Uvicorn running on http://0.0.0.0:8989 (Press CTRL+C to quit)
[2024-07-31 08:31:36,569]\tINFO\t[server.py:shutdown:258]\t>> Shutting down
[2024-07-31 08:31:36,673]\tINFO\t[on.py:shutdown:67]\t>> Waiting for application shutdown.
[2024-07-31 08:31:36,677]\tINFO\t[main.py:lifespan:22]\t>> ::SERVER SHUTTING DOWN::2024-07-31 08:31:36.677643
[2024-07-31 08:31:36,679]\tINFO\t[on.py:shutdown:76]\t>> Application shutdown complete.
[2024-07-31 08:31:36,680]\tINFO\t[server.py:_serve:92]\t>> Finished server process [73224]
[2024-07-31 08:31:36,681]\tERROR\t[logger.py:handle_exception:86]\t>> System-level unexpected exception
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/home/jungwoo/my_qa_bot/fastapi/main.py", line 53, in <module>
    uvicorn.run(
  File "/home/jungwoo/my_qa_bot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/jungwoo/my_qa_bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/jungwoo/my_qa_bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/jungwoo/my_qa_bot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
